version: 2.1
default_settings: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/
commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  print_wordflow_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
workflows:
  say-hello-workflow:
    jobs:
      - print_wordflow_id