version: 2.1
default_settings: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/
jobs:
  print_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: print error
          command: echo "error"
          shell: bash
          when: on_fail
workflows:
  my_workflow:
    jobs:
      - print_error